systemName = "Our House"      # Label for the system

longitude = 43.6
latitude = "!!SECRET(latitude)"       # Get latitude value from secrets.toml
postcode = "!!SECRET(postcode)"

mqttBroker = "!!CONSTANT(mqttBroker)"  # Hostname or IP of MQTT Broker
mqttPort = 1883               # MQTT Broker port
mqttClientID = "aghast"       # MQTT Client ID

logEvents = false             # A LOT of stuff will be logged if this is true!

controlPort = 46445           # HTTP port for back-end admin control

# List of Integrations we want enabled
integrations = [
  "time",         # the Time integration MUST be enabled
#  "automation",
  "network",
#  "datalogger",
#  "daikin",
  "influx",
#  "scraper",
  "tuya",
]
