systemName = "Our House"

longitude = 43.5
latitude = 2.0

mqttBroker = "mediaserver01"
mqttPort = 1883
mqttClientID = "aghast"

logEvents = false       # A LOT of stuff will be logged if this is true!

integrations = [
  "time",
  "network",
  "datalogger",
  "daikin",
]
