SystemName = "Our House"      # Label for the system
Postcode = "!!SECRET(postcode)"

MqttBroker = "!!CONSTANT(mqttBroker)"  # Hostname or IP of MQTT Broker
MqttPort = 1883               # MQTT Broker port
MqttClientID = "aghast-DEV"   # MQTT Client ID
MqttUsername = ""
MqttPassword = ""
MqttBaseTopic = "aghast"

LogEvents = true              # A LOT of stuff will be logged if this is true!

ControlPort = 46445           # HTTP port for back-end admin control

# List of Integrations we want enabled
Integrations = [
  "time",         # the Time integration MUST be enabled
  "automation",
#  "datalogger",
#  "daikin",
  "hostchecker",
#  "influx",
#  "pimqttgpio",
#  "postgres",
#  "scraper",
#  "tuya",
#  "zigbee2mqtt",
]
