[Inverter.C0E434E69F27]          # The key is the unpunctuated MAC address of the unit
  label = "Steve's Office"       # A user-friendly label for the unit - must be unique
  
[Inverter.C0E434E6A3C6]
  label = "Dining Room"

[Inverter.C0E434E60BC6]
  label = "Spare Bedroom"

[Inverter.C0E434E615C3]
  label = "Paul's Studio"

[Inverter.C0E434E60BA0]
  label = "Master Bedroom"

[Inverter.D8C0A664EDEE]
  label = "Living Room"

[Inverter.706655B5CD75]
  label = "Hall"

[Inverter.D8C0A664E830]
  label = "Music Room"
  