LogDir = "/tmp"     # Don't use /tmp for real!

[[Logger]]
  Name = "Latencies"
  LogFile = "wonkyPiLatency.csv"
  Integration = "Network"
  DeviceType = "HostChecker"
  DeviceName = "+"
  EventName = "Latency"
  FlushEvery = 2

[[Logger]]
  Name = "StevesRoomTemp"
  LogFile = "stevesTemp.csv"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Steve's Office"
  EventName = "Temperature"
  FlushEvery = 2

[[Logger]]
  Name = "LivingRoomTemp"
  LogFile = "salonTemp.csv"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Living Room"
  EventName = "Temperature"
  FlushEvery = 2
  
[[Logger]]
  Name = "AllTemps"
  LogFile = "allTemps.csv"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "+"
  EventName = "Temperature"
  FlushEvery = 2
  