logDir = "/tmp"     # Don't use /tmp for real!

[Logger.Latencies]
  logFile = "wonkyPiLatency.csv"
  integration = "Network"
  deviceType = "HostChecker"
  deviceName = "+"
  eventName = "Latency"
  flushEvery = 2

[Logger.StevesRoomTemp]
  logFile = "stevesTemp.csv"
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Steve's Office"
  eventName = "Temperature"
  flushEvery = 10
  
[Logger.AllTemps]
  logFile = "allTemps.csv"
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "+"
  eventName = "Temperature"
  flushEvery = 50
  