# InfluxDB connection details
Bucket = "aghast"
Org = "aghast"
Token = "!!SECRET(influxToken)"
URL = "http://localhost:8086"

# Data to log
[[Logger]]
  Name = "OutsideTemp"      
  EventName = "Daikin/Inverter/Hall/OutsideTemperature"
  DataType = "float"                    # Either 'float', 'integer', or 'string'
  
[[Logger]]
  Name = "HallTemp"   
  EventName = "Daikin/Inverter/Hall/Temperature"
  DataType = "float"

[[Logger]]
  Name = "MusicTemp"       
  EventName = "Daikin/Inverter/Music Room/Temperature"
  DataType = "float"

[[Logger]]
  Name = "SalonTemp"      
  EventName = "Daikin/Inverter/Living Room/Temperature"
  DataType = "float"

[[Logger]]
  Name = "DiningTemp"         
  EventName = "Daikin/Inverter/Dining Room/Temperature"
  DataType = "float"

[[Logger]]
  Name = "MasterBedTemp"     
  EventName = "Daikin/Inverter/Master Bedroom/Temperature"
  DataType = "float"