# InfluxDB connection details
Bucket = "aghast"
Org = "aghast"
Token = "!!SECRET(influxToken)"
URL = "http://localhost:8086"

# Data to log
[[Logger]]  
  Name = "MusicActualTemp" 
  Topic = "pizero01/gpio/sensor/dht22_temperature"
  DataType = "float"     

[[Logger]]
  Name = "SteveOfficeUnitTemp"       
  Topic = "daikin2mqtt/Steve_Office/sensors"
  Key = "unit_temp"                      # payload is JSON, so must specify key
  DataType = "float"
