# InfluxDB connection details
bucket = "aghast"
org = "aghast"
token = "!!SECRET(influxToken)"
url = "http://localhost:8086"

# Data to log
[Logger.OutsideTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Hall"         
  eventName = "OutsideTemperature"
  type = "float"                    # Either 'float', 'integer', or 'string'
  
[Logger.HallTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Hall"           
  eventName = "Temperature"
  type = "float"

[Logger.MusicTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Music Room"           
  eventName = "Temperature"
  type = "float"

[Logger.SalonTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Living Room"           
  eventName = "Temperature"
  type = "float"

[Logger.DiningTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Dining Room"           
  eventName = "Temperature"
  type = "float"

[Logger.MasterBedTemp]
  integration = "Daikin"
  deviceType = "Inverter"
  deviceName = "Master Bedroom"           
  eventName = "Temperature"
  type = "float"