# InfluxDB connection details
Bucket = "aghast"
Org = "aghast"
Token = "!!SECRET(influxToken)"
URL = "http://localhost:8086"

# Data to log
[[Logger]]
  Name = "OutsideTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Hall"         
  EventName = "OutsideTemperature"
  DataType = "float"                    # Either 'float', 'integer', or 'string'
  
[[Logger]]
  Name = "HallTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Hall"           
  EventName = "Temperature"
  DataType = "float"

[[Logger]]
  Name = "MusicTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Music Room"           
  EventName = "Temperature"
  DataType = "float"

[[Logger]]
  Name = "SalonTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Living Room"           
  EventName = "Temperature"
  DataType = "float"

[[Logger]]
  Name = "DiningTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Dining Room"           
  EventName = "Temperature"
  DataType = "float"

[[Logger]]
  Name = "MasterBedTemp"
  Integration = "Daikin"
  DeviceType = "Inverter"
  DeviceName = "Master Bedroom"           
  EventName = "Temperature"
  DataType = "float"