# Configuration for Raspberry Pi MQTT GPIO (pi-mqtt-gpio) Integration
# See https://github.com/flyte/pi-mqtt-gpio for the server

[[Sensor]]
  Name           = "MusicRoomTemp"  # A unique name, will be subtopic if forwarding MQTT
  TopicPrefix    = "pizero01/gpio"  # This must match the topic_prefix setting on the Pi
  SensorType     = "dht22_temperature"
  ValueType      = "float" # One of "string", "integer", or "float"
  RoundToInteger = false
  ForwardEvent   = true    # Do not create an AGHAST Event for each value received   
  ForwardMQTT    = true    # Create an AGHAST-sourced MQTT message for each value

[[Sensor]]
  Name           = "MusicRoomHumidity"
  TopicPrefix    = "pizero01/gpio"  
  SensorType     = "dht22_humidity"
  ValueType      = "float" 
  RoundToInteger = true   # Round a float to nearest integer and then handle as integer
  ForwardAghast  = false  # Do not create an AGHAST Event for each value received   
  ForwardMQTT    = true   # Create an AGHAST-sourced MQTT message for each value
  