# Postgres connection details
PgHost = "localhost"
PgPort = "5432"        # Use quotes for this
PgUser = "steve"
PgPassword = "aghast"  # Use a !!SECRET in production
PgDatabase = "aghast"

[[Logger]]  
  Name = "MusicActualTemp" 
  Topic = "pizero01/gpio/sensor/dht22_temperature"
  DataType = "float"                    # Either 'float', 'integer', or 'string'
  
[[Logger]]  
  Name = "LivingRoomActualTemp" 
  Topic = "pizero02/gpio/sensor/dht22_temperature"
  DataType = "float"                    # Either 'float', 'integer', or 'string'

[[Logger]]
  Name = "SteveOfficeUnitTemp"       
  Topic = "daikin2mqtt/Steve_Office/sensors"
  Key = "unit_temp"                      # payload is JSON, so must specify key
  DataType = "float"
 
