# Postgres connection details
PgHost = "localhost"
PgPort = "5432"        # Use quotes for this
PgUser = "steve"
PgPassword = "aghast"  # Use a !!SECRET in production
PgDatabase = "aghast"

# Outside

[[Logger]]  
  Name = "OutsideUnitTemp"      
  EventName = "Daikin/Inverter/Hall/OutsideTemperature"
  DataType = "float"                    # Either 'float', 'integer', or 'string'

# Ground floor Units

[[Logger]]
  Name = "DininRoomgUnitTemp"         
  EventName = "Daikin/Inverter/Dining Room/Temperature"
  DataType = "float"
  
[[Logger]]
  Name = "HallUnitTemp"   
  EventName = "Daikin/Inverter/Hall/Temperature"
  DataType = "float"
  
[[Logger]]
  Name = "LivingRoomUnitTemp"      
  EventName = "Daikin/Inverter/Living Room/Temperature"
  DataType = "float"
  
[[Logger]]
  Name = "MusicRoomUnitTemp"       
  EventName = "Daikin/Inverter/Music Room/Temperature"
  DataType = "float"

# Ground floor monitors

[[Logger]]
  Name = "MusicRoomActualTemp"
  EventName = "PiMqttGpio/Sensor/pizero01/gpio/dht22_temperature"
  DataType = "float"

[[Logger]]
  Name = "MusicRoomHumidity"
  EventName = "PiMqttGpio/Sensor/pizero01/gpio/dht22_humidity"
  DataType = "integer"

[[Logger]]
  Name = "LivingRoomActualTemp"
  EventName = "PiMqttGpio/Sensor/pizero02/gpio/dht22_temperature"  
  DataType = "float"

[[Logger]]
  Name = "LivingRoomHumidity"
  EventName = "PiMqttGpio/Sensor/pizero02/gpio/dht22_humidity"  
  DataType = "integer"

# First floor Units

[[Logger]]
  Name = "MasterBedUnitTemp"     
  EventName = "Daikin/Inverter/Master Bedroom/Temperature"
  DataType = "float"

[[Logger]]
  Name = "PaulsStudioUnitTemp"     
  EventName = "Daikin/Inverter/Paul's Studio/Temperature"
  DataType = "float"

[[Logger]]
  Name = "StevesOfficeUnitTemp"     
  EventName = "Daikin/Inverter/Steve's Office/Temperature"
  DataType = "float"

[[Logger]]
  Name = "SpareRoomUnitTemp"     
  EventName = "Daikin/Inverter/Spare Bedroom/Temperature"
  DataType = "float"
 