# Example Time configuration
# N.B. Times must be double-quoted as "HH:MM:SS"

Longitude = "!!SECRET(longitude)" # Required for Sunset/Sunrise calcs
Latitude = "!!SECRET(latitude)"   # Get latitude value from secrets.toml

[[Event]]
  Name = "NightOffPeakStarts"
  Time = "00:50:05"               # Plus 5s to be sure!

[[Event]]
  Name = "NightOffPeakEnds"
  Time = "06:50:00"

[[Event]]
  Name = "LunchtimeOffPeakStarts"
  Time = "12:20:05"

[[Event]]
  Name = "LunchtimeOffPeakEnds"
  Time = "14:20:00"

[[Event]]
  Name = "Test1"
  Time = "11:58:00"

[[Event]]
  Name = "Test2"
  Time = "16:54:00"

# [[Event]]
# Name = "TenBeforeWork"
# Time = "16:39:00"

[[Event]]
  Name = "MorningHeatingOn"
  Time = "06:30:00"          # 20mins before off-peak ends

[[Event]]
  Name = "Sunrise"
  Daily = "Sunrise"
  OffsetMins = 0

[[Event]]
  Name = "FifteenBeforeSunset"
  Daily = "Sunset"
  OffsetMins = -15
