# Configuration for the Zigbee2MQTT Integration
# See https://www.zigbee2mqtt.io/ for the server

TopicRoot = "zigbee2mqtt"

[[Socket]]
  FriendlyName = "Towel_Rail"

[[Socket]]
  FriendlyName = "Office_Socket"

[[Socket]]
  FriendlyName = "Stairway_Socket"


