name = "ExampleMQTT"
description = "Respond to an MQTT event"
enabled = true

[event]
  topic = "aghast/client/DemoButton"

[condition]
  integration = "PiMqttGpio"
  name = "MusicRoomTemp"
  is = "<"                # one of: "=", "!=", "<", ">", 
  value = 17.0

[action.1]
  integration = "Daikin"
  deviceLabel = "Steve's Office"
  execute = [ { control = "temperature", setting = 21.0 },
              { control = "mode",        setting = "Heat" },
              { control = "power",       setting = "on" } ]

