Name = "MorningeWarmup"
Description = "Warm upstairs"
Enabled = true

[Event]
  Topic = "aghast/time/events/MorningPrewarming"

[Action.1]
  Topic = "daikin2mqtt/Steve_Office/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 18.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = true } ]
[Action.2]
  Topic = "daikin2mqtt/Paul_Studio/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 18.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = true } ]

[Action.3]
  Topic = "daikin2mqtt/Master_Bedroom/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 18.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "fan",         Setting = "3" },
              { Control = "power",       Setting = true } ]

[Action.4]
  Topic = "daikin2mqtt/Dining_Room/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 18.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = true } ]
