Name = "MorningHeatingStart"
Description = "Main Downstairs Heaters On"
Enabled = false
EventTopic = "aghast/time/events/MorningHeatingOn"

[Action.1]
  Topic   = "daikin2mqtt/Hall/set/controls"
  Payload = '{ "set_temp": 23.0, "mode": "Heat", "power": true }'


[Action.3]
  Topic = "daikin2mqtt/Music_Room/set/controls"
  Payload = '{ "set_temp": 20.0, "mode": "Heat", "power": true }'
