Name = "MorningHeatingStart"
Description = "Main Downstairs Heaters On"
Enabled = true

[Event]
  Topic = "aghast/time/events/MorningHeatingOn"

[Action.1]
  Topic = "daikin2mqtt/Hall/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 23.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = true } ]

# [Action.2]
#   Integration = "Daikin"
#   DeviceLabel = "Living Room"
#   Execute = [ { Control = "tset_temp", Setting = 18.0 },
#               { Control = "mode",        Setting = "Heat" },
#               { Control = "power",       Setting = true } ]  

[Action.3]
  Topic = "daikin2mqtt/Music_Room/set/controls"
  Execute = [ { Control = "set_temp",    Setting = 20.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = true } ]  

