Name = "MorningOfficeWarmup"
Description = "Warm up the office"
Enabled = false

[Event]
  Integration = "Time"
  # deviceType  = "Events"
  # deviceName  = "TimedEvent"
  # eventName   = "TenBeforeWork"
 DeviceType = "Ticker"
 DeviceName = "SystemTicker"
 EventName = "Minute"

[action.1]
  Integration = "Daikin"
  DeviceLabel = "Steve's Office"
  Execute = [ { Control = "temperature", Setting = 20.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = "on" } ]
 