name = "MorningHeatingStart"
description = "Main Downstairs Heaters On"
enabled = true

[event]
  integration = "Time"
  deviceType  = "Events"
  deviceName  = "TimedEvent"
  eventName   = "MorningHeatingOn"

[action.1]
  integration = "Daikin"
  deviceLabel = "Hall"
  execute = [ { control = "temperature", setting = 21.0 },
              { control = "mode",        setting = "Heat" },
              { control = "power",       setting = "on" } ]

[action.2]
  integration = "Daikin"
  deviceLabel = "Living Room"
  execute = [ { control = "temperature", setting = 19.0 },
              { control = "mode",        setting = "Heat" },
              { control = "power",       setting = "on" } ]  

[action.3]
  integration = "Daikin"
  deviceLabel = "Music Room"
  execute = [ { control = "temperature", setting = 18.0 },
              { control = "mode",        setting = "Heat" },
              { control = "power",       setting = "on" } ]  
