Name = "MorningHeatingStart"
Description = "Main Downstairs Heaters On"
Enabled = true

[Event]
  Name = "Time/Events/TimedEvent/MorningHeatingOn"

[Action.1]
  Integration = "Daikin"
  DeviceLabel = "Hall"
  Execute = [ { Control = "temperature", Setting = 23.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = "on" } ]

# [Action.2]
#   Integration = "Daikin"
#   DeviceLabel = "Living Room"
#   Execute = [ { Control = "temperature", Setting = 18.0 },
#               { Control = "mode",        Setting = "Heat" },
#               { Control = "power",       Setting = "on" } ]  

[Action.3]
  Integration = "Daikin"
  DeviceLabel = "Music Room"
  Execute = [ { Control = "temperature", Setting = 20.0 },
              { Control = "mode",        Setting = "Heat" },
              { Control = "power",       Setting = "on" } ]  

#[Action.4]
#  Integration = "Daikin"
#  DeviceLabel = "Spare Bedroom"
#  Execute = [ { Control = "temperature", Setting = 16.0 },
#              { Control = "mode",        Setting = "Heat" },
#              { Control = "power",       Setting = "on" } ]  

