Name = "MorningWarmup"
Description = "Warm upstairs"
Enabled = false
EventTopic = "aghast/time/events/MorningPrewarming"

[Action.1]
  Topic = "daikin2mqtt/Steve_Office/set/controls"
  Payload = '{ "set_temp": 18.0, "mode": "Heat", "power": true }'

[Action.2]
  Topic = "daikin2mqtt/Paul_Studio/set/controls"
  Payload = '{ "set_temp": 18.0, "mode": "Heat", "power": true }'

[Action.3]
  Topic = "daikin2mqtt/Master_Bedroom/set/controls"
  Payload = '{ "set_temp": 18.0, "mode": "Heat", "power": true }'

[Action.4]
  Topic = "daikin2mqtt/Dining_Room/set/controls"
  Payload = '{ "set_temp": 18.0, "mode": "Heat", "power": true }'
