Name = "SocketTest"
Description = "Test Zigbee2MQTT"
Enabled = true

[Event]
  Topic = "aghast/time/tickers/minutes"

[Action.1]
  Topic = "zigbee2mqtt/Office_Socket/set"
  Execute = [ { Control = "state", Setting = "TOGGLE" } ]

