Name = "StairwayZapperOff"
Description = "Turn zapper off at sunrise"
Enabled = true
EventTopic = "aghast/time/events/Sunrise"

[Action.1]
  Topic = "zigbee2mqtt/Stairway_Socket/set"
  Payload = '{ "state": "OFF" }'
