Name        = "StairwayZapperOn"
Description = "Turn zapper on at night-time off-peak start"
Enabled     = true
EventTopic  = "aghast/time/events/NightOffPeakStarts"

[Action.1]
  Topic   = "zigbee2mqtt/Stairway_Socket/set"
  Payload = '{ "state": "ON" }'
