Name = "StairwayZapperOff"
Description = "Turn zapper off at sunrise"
Enabled = true

[Event]
  Topic = "aghast/time/events/Sunrise"

[Action.1]
  Topic = "zigbee2mqtt/Stairway_Socket/set"
  Execute = [ { Control = "state", Setting = "OFF" } ]

