Name = "StairwayZapperOn"
Description = "Turn zapper on at night-time off-peak start"
Enabled = true

[Event]
  Name = "Time/Events/TimedEvent/NightOffPeakStarts"
  Topic = "aghast/time/events/NightOffPeakStarts"

[Action.1]
  Topic = "zigbee2mqtt/Stairway_Socket/set"
  Execute = [ { Key = "state", Value = "ON" } ]
