Name        = "TowelRailOffLunch"
Description = "Turn Towel-Rail off for lunchtime off-peak"
Enabled     = true
EventTopic  = "aghast/time/events/LunchtimeOffPeakEnds"

[Action.1]
  Topic   = "zigbee2mqtt/Towel_Rail/set"
  Payload = '{ "state": "OFF" }'
