Name = "TowelRailOffLunch"
Description = "Turn Towel-Rail off for lunchtime off-peak"
Enabled = true

[Event]
  Name = "Time/Events/TimedEvent/LunchtimeOffPeakEnds"
#  Name = "Time/Ticker/SystemTicker/Minute"

[Action.1]
  Integration = "Zigbee2MQTT"
  DeviceLabel = "Towel_Rail"
  Execute = [ { Control = "state", Setting = "OFF" } ]
