Name = "TowelRailOnNight"
Description = "Turn Towel-Rail on during night-time off-peak"
Enabled = true

[Event]
  Topic = "aghast/time/events/TowelRailOn"

[Action.1]
  Topic = "zigbee2mqtt/Towel_Rail/set"
  Execute = [ { Control = "state", Setting = "ON" } ]
