Name = "TowelRailOffMorning"
Description = "Turn Towel-Rail off for overnight off-peak"
Enabled = true

[Event]
  Name = "Time/Events/TimedEvent/NightOffPeakEnds"
#  Name = "Time/Ticker/SystemTicker/Minute"

[Action.1]
  Integration = "Tuya"
  DeviceLabel = "Towel Rail Socket"
  Execute = [ { Control = "power", Setting = "off" } ]
