Name = "TowelRailOnNight"
Description = "Turn Towel-Rail on during night-time off-peak"
Enabled = true

[Event]
  Name = "Time/Events/TimedEvent/TowelRailOn"
#  Name = "Time/Ticker/SystemTicker/Minute"

[Action.1]
  Integration = "Zigbee2MQTT"
  DeviceLabel = "Towel_Rail"
  Execute = [ { Control = "state", Setting = "ON" } ]
