Name = "TowelRailOnLunch"
Description = "Turn Towel-Rail on for lunchtime off-peak"
Enabled = true

[Event]
  Topic = "aghast/time/events/LunchtimeOffPeakStarts"

[Action.1]
  Topic = "zigbee2mqtt/Towel_Rail/set"
  Execute = [ { Control = "state", Setting = "ON" } ]
